repos:
  - repo: https://github.com/psf/black
    # Black version
    rev: 25.12.0
    hooks:
      # Run the Black formatter
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.14.9
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/PyCQA/isort
    # isort version
    rev: 7.0.0
    hooks:
      # Sort imports with isort
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]

  - repo: https://github.com/kynan/nbstripout
    # nbstripout version
    rev: 0.8.2
    hooks:
      # Strip output cells from Jupyter notebooks before committing to keep notebooks clean and reduce merge conflicts
      - id: nbstripout
        stages: [ commit ]
