name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - run: sudo apt-get install libxml2 libxml2-dev libxslt-dev python-dev-is-python3
      - name: Sync project dependencies
        run: uv sync --locked --extra lint
      - run: uv run ruff check src
      - name: Run mypy
        run: |
          if [[ '${{ matrix.python-version }}' == '3.11' ]]; then
            echo "Skipping type checking on Python 3.11"
          else
            uv run mypy src
          fi
      - run: uv run pyroma . --min=10
      - run: |
          uv run python -m retrocast.cli --help |& grep -q 'Usage:'
